// Code generated by Icestudio 0.8.1w202112300112

`default_nettype none

//---- Top entity
module main (
 output v7b511e
);
 wire w0;
 assign v7b511e = w0;
 vfebcfe v14f857 (
  .v9fb85f(w0)
 );
endmodule

//---- Top entity
module vfebcfe (
 output v9fb85f
);
 wire w0;
 assign v9fb85f = w0;
 vfebcfe_vb2eccd vb2eccd (
  .q(w0)
 );
endmodule

//---------------------------------------------------
//-- bit-1
//-- - - - - - - - - - - - - - - - - - - - - - - - --
//-- Constant bit 1
//---------------------------------------------------

module vfebcfe_vb2eccd (
 output q
);
 //-- Constant bit-1
 assign q = 1'b1;
 
 
endmodule
