// Code generated by Icestudio 0.9.2w202204260904
// Thu, 28 Apr 2022 08:35:07 GMT

// Testbench template

`default_nettype none
`timescale 10 ns / 1 ns


module main_tb
;
 
 // Simulation time: 100ns (10 * 10ns)
 parameter DURATION = 10;
 
 // Input/Output
 reg BUTTON = 0;
 wire LED;

 // Module instance
 main MAIN (
  .v2a5c04(BUTTON),
  .v60f428(LED)
 );
 
 initial begin
  // Dump vars to the output .vcd file
  $dumpvars(0, main_tb);
 

  #10 BUTTON=1;
  #10 BUTTON=0;
  #10 BUTTON=1;
  #10 BUTTON=0;

  $display("End of simulation");
  $finish;
 end
 
endmodule
