// Code generated by Icestudio 0.13.2w202501120101202501120101
//  #START Verilator Linter rules:
/* verilator lint_off PINMISSING */
/* verilator lint_off WIDTHTRUNC */
/* verilator lint_off WIDTHEXPAND */
//  #END Verilator Linter rules

`default_nettype none

//---- Top entity
module main (
 output v8bfc7f,
 output [6:0 ] vinit
);
 wire w0;
 assign v8bfc7f = w0;
 vfebcfe vb9eb2f (
  .v9fb85f(w0)
 );
 assign vinit = 7'b0000000;
endmodule

//---- Top entity
module vfebcfe (
 output v9fb85f
);
 wire w0;
 assign v9fb85f = w0;
 vfebcfe_vb2eccd vb2eccd (
  .q(w0)
 );
endmodule

//---------------------------------------------------
//-- bit-1
//-- - - - - - - - - - - - - - - - - - - - - - - - --
//-- Constant bit 1
//---------------------------------------------------

module vfebcfe_vb2eccd (
 output q
);
 //-- Constant bit-1
 assign q = 1'b1;
 
 
endmodule
