# -*- coding: utf-8 -*-
# -- This file is part of the Apio project
# -- (C) 2016-2019 FPGAwars
# -- Author Jesús Arroyo
# -- License GPLv2
"""Manage the apio remote configuration"""

# pylint: disable=duplicate-code

import json
from enum import Enum, unique
from datetime import datetime
from typing import Any
from pathlib import Path
import requests
import json5
from apio.common.debug_util import is_debug
from apio.common.apio_console import cout, fatal_error, cerror
from apio.common.apio_styles import INFO, EMPH3
from apio.utils import util
from apio.common.proto_util import (
    proto_from_json_dict,
    proto_to_json_dict,
    check_is_required,
)
from apio.common.proto.stubs.apio_remote_config_pb2 import (
    CachedRemoteConfigSpec,
    RemoteConfigSpec,
    CachedRemoteConfigMetadata,
    RemoteConfigPackageSpec,
)

#


@unique
class RemoteConfigPolicy(Enum):
    """Represents possible requirements from the remote config."""

    # -- Config is being used but can be a cached value, as long that it's
    # -- not too old.
    CACHED_OK = 1
    # -- Config is being used and a fresh copy is that was fetch in this
    # -- invocation of Apio is required.
    GET_FRESH = 2


def get_datetime_stamp(dt: datetime | None = None) -> str:
    """Returns a string with time now as yyyy-mm-dd-hh-mm"""
    if dt is None:
        dt = datetime.now()
    return dt.strftime("%Y-%m-%d-%H-%M")


def days_between_datetime_stamps(ts1: str, ts2: str, default: Any) -> int:
    """Given two values generated by get_datetime_stamp(), return the
    number of days from ts1 to ts2. The value can be negative if ts2 is
    earlier than ts1. Returns the given 'default' value if either timestamp
    is invalid."""

    # -- The parsing format.
    fmt = "%Y-%m-%d-%H-%M"

    # -- Convert to timedates
    try:
        datetime1 = datetime.strptime(ts1, fmt)
        datetime2 = datetime.strptime(ts2, fmt)
    except ValueError:
        return default

    # -- Round to beginning of day.
    day1 = datetime(datetime1.year, datetime1.month, datetime1.day)
    day2 = datetime(datetime2.year, datetime2.month, datetime2.day)

    # -- Compute the diff in days.
    delta_days: int = (day2 - day1).days

    # -- All done.
    assert isinstance(delta_days, int)
    return delta_days


def minutes_between_datetime_stamps(ts1: str, ts2: str, default: Any) -> int:
    """Return the number of minutes from ts1 to ts2 or default if any of
    the timestamps is invalid."""

    # -- The parsing format.
    fmt = "%Y-%m-%d-%H-%M"

    # -- Convert to timedates
    try:
        datetime1 = datetime.strptime(ts1, fmt)
        datetime2 = datetime.strptime(ts2, fmt)
    except ValueError:
        return default

    # -- Calculate the diff in minutes.
    delta_minutes = int((datetime2 - datetime1).total_seconds() / 60)
    assert isinstance(delta_minutes, int), type(delta_minutes)
    return delta_minutes


class RemoteConfig:
    """Class for managing the apio remote config and its local cache
    ~/.apio/cached-remote-config.json
    """

    # -- Only these instance vars are allowed.
    __slots__ = (
        # "_profile_path",
        # "_packages_index_path",
        "remote_config_url",
        "remote_config_ttl_days",
        "remote_config_retry_minutes",
        "_remote_config_policy",
        "_cached_remote_config_path",
        "_cached_remote_config",
        # "preferences",
        # "installed_packages",
    )

    def __init__(
        self,
        home_dir: Path,
        # packages_dir: Path,
        remote_config_url_template: str,
        remote_config_ttl_days: int,
        remote_config_retry_minutes: int,
        remote_config_policy: RemoteConfigPolicy,
    ):
        """remote_config_url_template is a url string with the
        placeholder {major} and {minor} for the apio's major and minor
        version. '"""

        # pylint: disable=too-many-arguments
        # pylint: disable=too-many-positional-arguments

        # -- Sanity check
        assert isinstance(remote_config_ttl_days, int)
        assert 0 < remote_config_ttl_days <= 30

        # -- Sanity check
        assert isinstance(remote_config_retry_minutes, int)
        assert 0 < remote_config_retry_minutes <= (60 * 24)

        # -- Resolve and cache the remote config url. Replaced the placeholders
        # -- with the major and minor versions of apio. Path version is
        # -- not used.
        ver_tuple = util.get_apio_version_tuple()
        url = remote_config_url_template
        url = url.replace("{major}", str(ver_tuple[0]))
        url = url.replace("{minor}", str(ver_tuple[1]))

        self.remote_config_url: str = url

        # -- Save remote url ttl setting.
        self.remote_config_ttl_days: int = remote_config_ttl_days

        # -- Save the remote config fetch retry minutes.
        self.remote_config_retry_minutes: int = remote_config_retry_minutes

        # -- Save remote config policy.
        self._remote_config_policy: RemoteConfigPolicy = remote_config_policy

        # -- Verify that we resolved all the remote config URL placeholders.
        assert "{" not in self.remote_config_url, self.remote_config_url

        if is_debug(1):
            cout(f"Remote config url: {self.remote_config_url}")

        # -- Start with no remote config.
        self._cached_remote_config: CachedRemoteConfigSpec | None = None

        # -- Path to the local file with the cached remote config.
        self._cached_remote_config_path: Path = (
            home_dir / "cached-remote-config.json"
        )

        # -- Try to load the cached remote config. If found and read
        # -- successfully it mutates self._cached_remote_config
        self._maybe_load_cached_remote_config()

        # -- Apply config policy
        self._apply_remote_config_policy()

    @staticmethod
    def _announce_no_suitable_cached_config(reason: str):
        """Show a message indicating that the cached remote config is being
        skipped."""
        cout(f"No suitable cached remote config file ({reason}).")

    def _apply_remote_config_policy(self) -> None:
        """Called after loading the profile file, to apply the remote config
        policy for this invocation."""

        # -- Case 1: A fresh config is required for the current command.
        if self._remote_config_policy == RemoteConfigPolicy.GET_FRESH:
            self._maybe_fetch_and_update_remote_config(error_is_fatal=True)
            return

        # -- Case 2: A fresh config is optional but there is no cached
        # -- config so practically it's required.
        assert self._remote_config_policy == RemoteConfigPolicy.CACHED_OK
        if self._cached_remote_config is None:
            if is_debug(1):
                cout("Cached remote config is not available.", style=INFO)
            self._maybe_fetch_and_update_remote_config(error_is_fatal=True)
            return

        # -- Case 3: May need to fetch a new config but can continue with
        # -- the cached config in case of a fetch failure.
        #
        # -- Get the cached config metadata.
        check_is_required(
            self._cached_remote_config,
            "metadata",
            "metadata.loaded_at",
            "metadata.loaded_from",
        )
        metadata = self._cached_remote_config.metadata
        last_fetch_timestamp = metadata.loaded_at
        last_fetch_url = metadata.loaded_from

        # -- Determine if we need a new config because the remote config URL
        # -- was changed (e.g. with APIO_REMOTE_CONFIG_URL)
        url_changed = last_fetch_url != self.remote_config_url

        # -- Determine if there is time related reason to fetch a new config.
        datetime_stamp_now = get_datetime_stamp()
        days_since_last_fetch = days_between_datetime_stamps(
            last_fetch_timestamp, datetime_stamp_now, default=99999
        )
        time_valid = 0 <= days_since_last_fetch < self.remote_config_ttl_days

        minutes_since_refresh_failure = minutes_between_datetime_stamps(
            metadata.refresh_failure_on, datetime_stamp_now, default=None
        )
        refresh_failed_recently = (
            minutes_since_refresh_failure is not None
            and (
                0
                <= minutes_since_refresh_failure
                < self.remote_config_retry_minutes
            )
        )

        # -- Dump info for debugging.
        if is_debug(1):
            cout(
                f"{days_since_last_fetch=}, {time_valid=}, {url_changed=}",
                f"{minutes_since_refresh_failure=}, "
                f"{refresh_failed_recently=}",
                style=EMPH3,
            )

        # -- Fetch the new config if needed.
        if url_changed or not time_valid:
            reason = "source URL mismatch" if url_changed else "stale"
            self._announce_no_suitable_cached_config(reason=reason)
            if refresh_failed_recently:
                cout(
                    "Remote config fetch failed recently, "
                    + "will keep using cached config.",
                    style=INFO,
                )
            else:
                self._maybe_fetch_and_update_remote_config(
                    error_is_fatal=False
                )

    @property
    def data(self) -> RemoteConfigSpec:
        """Returns the remote config that is applicable for this invocation.
        Should not called if the context was initialized with NO_CONFIG."""
        assert self._cached_remote_config is not None
        return self._cached_remote_config.remote_config

    @property
    def metadata(self) -> CachedRemoteConfigMetadata:
        """Returns the remote config metadata. Should not be called
        if the context was initialized with NO_CONFIG."""
        assert self._cached_remote_config is not None
        return self._cached_remote_config.metadata

    def get_package_config(
        self,
        package_name: str,
    ) -> RemoteConfigPackageSpec:
        """Given a package name, return the remote config information with the
        version and fetch information.
        """
        return self.data.packages[package_name]

    def _maybe_load_cached_remote_config(self):
        """Try loading self._cached_remote_config from the local file
        cached_remote_config.json. If the file not found, or from a different
        version of apio do not do not change self._cached_remote_config.
        This method doesn't check for file age or staleness.
        """

        # -- If the file doesn't exist then do nothing.
        if not self._cached_remote_config_path.exists():
            self._announce_no_suitable_cached_config("no cache file")
            return

        # -- Read the cached remote config file as a json dict and extract its
        # -- fields. Handle invalid content gracefully, e.g. a corrupt or hand
        # -- edited file, since this runs on every apio command.
        try:
            with open(
                self._cached_remote_config_path, "r", encoding="utf8"
            ) as f:
                json_data = json.load(f)

            # -- If the cached remote config is not from the same apio version
            # -- as the current one, reject it.
            config_apio_version = json_data.get("metadata", {}).get(
                "loaded-by", ""
            )
            if config_apio_version != util.get_apio_version_str():
                self._announce_no_suitable_cached_config(
                    "Apio version mismatch"
                )
                return

        except (OSError, ValueError, AttributeError) as e:
            self._announce_no_suitable_cached_config("couldn't proto parse")
            cout(str(e), style=INFO)

        # -- Convert to proto.
        config_proto = proto_from_json_dict(json_data, CachedRemoteConfigSpec)
        if config_proto is None:
            self._announce_no_suitable_cached_config("Corrupt cached data")
            return

        # -- Update the remote config member.
        self._cached_remote_config = config_proto

    def _save(self):
        """Save the cached remote config to a file"""

        # -- Create the enclosing folder, if it does not exist yet
        file_path = self._cached_remote_config_path
        dir_path = file_path.parent
        if not dir_path.exists():
            dir_path.mkdir()

        # -- Convert proto to json dict
        json_dict = proto_to_json_dict(self._cached_remote_config)

        # -- Write to file.
        with open(self._cached_remote_config_path, "w", encoding="utf8") as f:
            json.dump(json_dict, f, indent=2)

        # -- Dump for debugging.
        if is_debug(1):
            cout("Saved cached remote config:", style=EMPH3)
            cout(json.dumps(json_dict, indent=2))

    def _handle_soft_config_refresh_failure(
        self, *, error_msg_lines: list[str]
    ):
        """Called to handle a soft failure of a remote config refresh.
        That is, an error, from which we recover by using the cached
        remote config."""

        # -- Sanity check, the cached config exists.
        assert self._cached_remote_config is not None

        # -- Print the soft warning.
        if error_msg_lines:
            cerror(*error_msg_lines)

        cout("Will try again at a latter time.", style=INFO)

        # -- Memorize the time of the attempt so we don't retry too often.
        self._cached_remote_config.metadata.refresh_failure_on = (
            get_datetime_stamp()
        )
        self._save()

    def _maybe_fetch_and_update_remote_config(
        self, *, error_is_fatal: bool
    ) -> None:
        """Try to fetch remote config and if fetched successfully update in
        self."""

        # pylint: disable=broad-exception-caught

        # -- Fetch the config text. Returns None if error_is_fatal=False and
        # -- fetch failed.
        remote_config_text: str | None = self._fetch_remote_config_text(
            error_is_fatal=error_is_fatal
        )

        if remote_config_text is None:
            # -- Sanity check, If error_is_fatal, _fetch_remote_config_text()
            # -- wouldn't return with None.
            assert not error_is_fatal
            return

        # -- Print the file's content for debugging
        if is_debug(1):
            cout(remote_config_text)

        try:
            json_dict = json5.loads(remote_config_text)
        except Exception as e:
            error_msg = "Failed to parse the fetched Apio remote config json."
            if error_is_fatal:
                fatal_error(error_msg, cause=e)
            self._handle_soft_config_refresh_failure(
                error_msg_lines=[error_msg, f"{e}"]
            )
            return

        # -- Convert the remote config json to proto.
        remote_config = proto_from_json_dict(json_dict, RemoteConfigSpec)
        if remote_config is None:
            error_msg = "Remote config data corrupt (proto parsing failed)"
            if error_is_fatal:
                fatal_error(error_msg)
            self._handle_soft_config_refresh_failure(
                error_msg_lines=[error_msg]
            )
            return

        # -- Construct the metadata field.
        metadata = CachedRemoteConfigMetadata(
            loaded_by=util.get_apio_version_str(),
            loaded_at=get_datetime_stamp(),
            loaded_from=self.remote_config_url,
        )

        # -- Update the cached config member.
        self._cached_remote_config = CachedRemoteConfigSpec(
            remote_config=remote_config, metadata=metadata
        )

        # -- Flush to disk.
        self._save()

    def _fetch_remote_config_text(self, error_is_fatal: bool) -> str | None:
        """Fetches and returns the apio remote config JSON text. In case
        of an error, returns None."""

        # pylint: disable=broad-exception-caught

        # -- Announce the remote config url
        cout(f"Fetching '{self.remote_config_url}'")

        # -- If the URL has a file protocol, read from the file. This
        # -- is used mostly for testing of a new package version.
        if self.remote_config_url.startswith("file://"):
            file_path = self.remote_config_url[7:]
            try:
                with open(file_path, encoding="utf-8") as f:
                    file_text = f.read()
            except Exception as e:
                # -- Since local config file can't be fixed with a fresh fetch
                # -- from a remote server, we treat this as a fatal error.
                fatal_error(
                    "Failed to read a local config file.",
                    cause=e,
                )

            # -- Local file read OK.
            return file_text

        # -- Here is the normal case where the config url is not of a local
        # -- file but at a remote URL.

        # -- Fetch the remote config. With timeout = 10, this failed a
        # -- few times on github workflow tests so increased to 25.
        exception: Exception | None = None
        try:
            resp: requests.Response = requests.get(
                self.remote_config_url, timeout=25
            )
        except Exception as e:
            exception = e

        error_msg = "Downloading of the latest Apio remote config file failed."

        # -- Handle the case of an exception. This is the preferable option
        # -- since it provides to fatal_error() a more detailed context of
        # -- the error (which can be viewed with APIO_DEBUG=1)
        if exception is not None:
            if error_is_fatal:
                fatal_error(error_msg, cause=exception)
            self._handle_soft_config_refresh_failure(
                error_msg_lines=[error_msg, str(exception)]
            )
            return None

        # -- Handle the case of a status error with no exception.
        if resp.status_code != 200:
            error_lines = [
                error_msg,
                f"Expected HTTP status code 200, got {resp.status_code}.",
            ]
            if error_is_fatal:
                fatal_error(*error_lines)
            self._handle_soft_config_refresh_failure(
                error_msg_lines=error_lines
            )
            return None

        # -- Done ok.
        assert resp.text is not None
        return resp.text
