"""A manager class for  to dispatch the Apio SCONS targets."""

# -*- coding: utf-8 -*-
# -- This file is part of the Apio project
# -- (C) 2016-2019 FPGAwars
# -- Author Jesús Arroyo
# -- License GPLv2


import json
from pathlib import Path
from typing import Any
from apio.common.debug_util import is_debug
from apio.common.apio_console import cout, fatal_error
from apio.common.apio_styles import INFO, EMPH1
from apio.apio_context import ApioContext
from apio.managers.downloader import FileDownloader
from apio.utils import util

# -- NOTE: We perform verification using sha256 only, without verifying also
# -- its size. According to source on the internet, if using sha256, there
# -- is no need to check also the size.

# -- The name of the Xilinx parts index file at the root of the openxc7
# -- package.
PARTS_INDEX_FILE_NAME = "XILINX-PARTS-INDEX.json"


# -- The expected version of the parts index schema, stored in the
# -- top-level "schema" field. Apio does not choose an engine at run
# -- time: this number is the contract with the installed package, and
# -- one openxc7 release carries one engine.
# --
# -- Schema 7 is the new nextpnr-xilinx, installed under the same name.
# -- There is one chipdb file per die, and the index entry of each part
# -- names the file that part uses. The command line is
# -- `nextpnr-xilinx --device <part> --chipdb <file> -o xdc=<file>
# -- -o fasm=<file> --json <file> --report <file>`.
# --
# -- Schema 6 was the previous nextpnr-xilinx, one chipdb file per base
# -- part and the command line `nextpnr-xilinx --chipdb <file> --xdc ...`.
# -- This apio rejects it.
EXPECTED_SCHEMA_VERSION = 7


def _parts_index_path(apio_ctx: ApioContext) -> Path:
    """Path of the parts index inside the installed openxc7 package."""
    return apio_ctx.get_package_dir("openxc7") / PARTS_INDEX_FILE_NAME


def read_xilinx_parts_index(apio_ctx: ApioContext) -> dict[str, Any]:
    """Open the openxc7 parts index and check that its schema is the one
    this apio reads."""

    parts_index_path = _parts_index_path(apio_ctx)
    with open(parts_index_path, encoding="utf-8") as f:
        json_data = json.load(f)

    # -- Verify that the index has a schema version we understand.
    actual_schema_version = (
        json_data["schema"] if "schema" in json_data else "Unknown"
    )
    if actual_schema_version != EXPECTED_SCHEMA_VERSION:
        fatal_error(
            f"Unexpected schema version {actual_schema_version}, "
            f"expected {EXPECTED_SCHEMA_VERSION}"
        )
    return json_data


def chipdb_file_on_demand(
    apio_ctx: ApioContext,
    yosys_part: str,
) -> Path:
    """Given a xilinx yosys-part, it fetches the chipdb file on-demand and
    returns its path."""

    # pylint: disable=too-many-locals

    # -- Get the local chipdb dir in the installed openxc7 package.
    # -- The path of this dir is defined in packages.jsonc.
    openxc7_define_consts = apio_ctx.all_packages["openxc7"]["env"][
        "define-consts"
    ]
    assert "CHIPDB_DIR" in openxc7_define_consts, openxc7_define_consts
    chipdb_dir = Path(openxc7_define_consts["CHIPDB_DIR"])

    # -- Delete all *.tgz files in the chipdb dir, just in case they were
    # -- not deleted after extracting the chipdb file.
    for path in chipdb_dir.glob("*.tgz"):
        cout(f"Deleting a leftover chipdb archive {path.name}", style=INFO)
        path.unlink()

    # -- Read the xilinx parts index and check its schema.
    json_data = read_xilinx_parts_index(apio_ctx)
    parts_index_path = _parts_index_path(apio_ctx)

    # -- Lookup part information using yosys_part as a key. A missing
    # -- part is a fatal error that names it. There is no default.
    parts = json_data["parts"]
    if yosys_part not in parts:
        fatal_error(
            f"No such xilinx yosys part {yosys_part}",
            info=f"See {str(parts_index_path)} for the list of "
            "supported xilinx parts.",
        )

    part_info = parts[yosys_part]

    # -- Dump for debugging.
    if is_debug(1):
        cout("Part info:", style=EMPH1)
        cout(json.dumps(part_info, indent=2))

    # -- If a chipdb was not generated by the opensc7 package builder
    # -- there is nothing we can do.
    if not part_info["generated"]:
        fatal_error(
            f"Yosys xilinx part {yosys_part} exists but not generated",
            info="Ask the Apio team to generate it.",
        )

    # -- Part found and it was generated by the openxc7 package builder.
    # -- Extract local chipdb file and release asset information.

    chipdb_file_name = part_info["chipdb"]
    release_asset_name = part_info["asset"]

    expected_chipdb_sha256 = part_info["chipdb-sha256"]
    expected_release_asset_sha256 = part_info["asset-sha256"]

    chipdb_file_path = chipdb_dir / chipdb_file_name

    # -- If the chipdb file already exists in the chipdb dir and it
    # -- the expected sha256 checksum then we are good.
    if chipdb_file_path.exists():
        cout(f"Chipdb file found: {chipdb_file_name}")
        actual_asset_sha256 = util.compute_file_sha256(chipdb_file_path)
        if actual_asset_sha256 == expected_chipdb_sha256:
            return chipdb_file_path

        # -- Here when the chipdb sha256 doesn't match. We delete it and
        # -- continue as if it did not exist.
        cout(
            "Existing chipdb file has an unexpected checksum: "
            f"{actual_asset_sha256}",
            style=INFO,
        )
        cout(f"Deleting old chipdb file {chipdb_file_path.name}")
        chipdb_file_path.unlink()

    # -- Here the chipdb file doesn't exist so we need to fetch it from the
    # -- same github release from which the openxc7 package was downloaded.
    # -- This information is stored in install-packages.json and is cached
    # -- in-memory.
    package_install_info = apio_ctx.package_manager.installed_packages[
        "openxc7"
    ]
    openxc7_package_url = package_install_info["loaded-from"]

    # -- Construct the chipdb release asset url by replacing the file name
    # -- in the package url.
    asset_url = (
        openxc7_package_url.rsplit("/", 1)[0] + "/" + release_asset_name
    )

    # -- Fetch the chipdb release asset.
    cout(f"Fetching {release_asset_name}")
    downloader = FileDownloader(asset_url, chipdb_dir)
    downloader.download()

    # -- Check that the sha256 of the downloaded asset matches the expected
    # -- shat256 we found in the part index.
    asset_local_path = chipdb_dir / release_asset_name
    actual_asset_sha256 = util.compute_file_sha256(asset_local_path)
    if actual_asset_sha256 != expected_release_asset_sha256:
        fatal_error(
            f"Downloaded chipdb asset has an unexpected checksum: "
            f"{actual_asset_sha256}",
            f"Expected {expected_release_asset_sha256}",
        )

    # -- Asset file was verified OK. Unpack it to extract the chipdb file.
    util.unpack_tgz(asset_local_path, dest_dir=chipdb_dir)

    actual_asset_sha256 = util.compute_file_sha256(chipdb_file_path)
    if actual_asset_sha256 != expected_chipdb_sha256:
        fatal_error(
            f"Chipdb file has an expected checksum {actual_asset_sha256}",
            f"Expected {expected_chipdb_sha256}",
        )

    # -- Here when the extracted chipdb file is ok.
    cout("Chipdb checksum verified.")

    # -- Delete the downloaded asset, we don't need it anymore.
    asset_local_path.unlink()

    # -- All done, return with the chipdb file path.
    return chipdb_file_path
