"""A manager class for  to dispatch the Apio SCONS targets."""

# -*- coding: utf-8 -*-
# -- This file is part of the Apio project
# -- (C) 2016-2019 FPGAwars
# -- Author Jesús Arroyo
# -- License GPLv2


import json
from pathlib import Path
from typing import Any
from apio.common.debug_util import is_debug
from apio.common.apio_console import cout, fatal_error
from apio.common.apio_styles import EMPH1
from apio.apio_context import ApioContext

# -- NOTE: We perform verification using sha256 only, without verifying also
# -- its size. According to source on the internet, if using sha256, there
# -- is no need to check also the size.

# -- The name of the Xilinx parts index file at the root of the openxc7
# -- package.
PARTS_INDEX_FILE_NAME = "XILINX-PARTS-INDEX.json"


# -- The expected version of the parts index schema, stored in the
# -- top-level "schema" field. This number is the contract with the
# -- installed openxc7 package: any other version is rejected.
# --
# -- In schema 7 there is one chipdb file per die, and the index entry
# -- of each part names the file that part uses.
EXPECTED_SCHEMA_VERSION = 8


def _parts_index_path(apio_ctx: ApioContext) -> Path:
    """Path of the parts index inside the installed openxc7 package."""
    return apio_ctx.get_package_dir("openxc7") / PARTS_INDEX_FILE_NAME


def _read_xilinx_parts_index(parts_index_path: Path) -> dict[str, Any]:
    """Open the openxc7 parts index and check that its schema is the one
    this apio reads."""

    # -- Read and parse the JSON file.
    with open(parts_index_path, encoding="utf-8") as f:
        json_data = json.load(f)

    # -- Verify that the index has a schema version we understand.
    actual_schema_version = (
        json_data["schema"] if "schema" in json_data else "Unknown"
    )
    if actual_schema_version != EXPECTED_SCHEMA_VERSION:
        fatal_error(
            f"Unexpected schema version {actual_schema_version}, "
            f"expected {EXPECTED_SCHEMA_VERSION}"
        )
    return json_data


def chipdb_file_for_part(
    apio_ctx: ApioContext,
    yosys_part: str,
) -> Path:
    """Given a xilinx yosys-part, return the path to its matching
    chipdb file within the openxc7 package."""

    # -- Get the local chipdb dir in the installed openxc7 package.
    # -- The path of this dir is defined in packages.jsonc.
    openxc7_define_consts = apio_ctx.all_packages["openxc7"]["env"][
        "define-consts"
    ]
    assert "CHIPDB_DIR" in openxc7_define_consts, openxc7_define_consts
    chipdb_dir = Path(openxc7_define_consts["CHIPDB_DIR"])

    # -- Read the xilinx parts index and check its schema.
    parts_index_path = _parts_index_path(apio_ctx)
    json_data = _read_xilinx_parts_index(parts_index_path)

    # -- Lookup part information using yosys_part as a key. A missing
    # -- part is a fatal error that names it. There is no default.
    parts = json_data["parts"]
    if yosys_part not in parts:
        fatal_error(
            f"No such xilinx yosys part {yosys_part}",
            info=f"See {str(parts_index_path)} for the list of "
            "supported xilinx parts.",
        )

    part_info = parts[yosys_part]

    # -- Dump for debugging.
    if is_debug(1):
        cout("Part info:", style=EMPH1)
        cout(json.dumps(part_info, indent=2))

    # -- If a chipdb was not generated by the openxc7 package builder
    # -- there is nothing we can do.
    if not part_info["generated"]:
        fatal_error(
            f"Yosys xilinx part {yosys_part} exists but not generated",
            info="Ask the Apio team to generate it.",
        )

    # -- Part found and it was generated by the openxc7 package builder.
    # -- Extract local chipdb file and release asset information.

    chipdb_file_name = part_info["chipdb"]
    return chipdb_dir / chipdb_file_name
