// Code generated by Icestudio 0.9.2w202204260904
// Thu, 28 Apr 2022 08:35:07 GMT

// Testbench template

`default_nettype none
`timescale 10 ns / 1 ns


module main_tb
;
 
 // Simulation time: 100ns (10 * 10ns)
 parameter DURATION = 10;
 
 // Input/Output
 wire LED;
 
 // Module instance
 main MAIN (
  .v8bfc7f(LED)
 );
 
 initial begin
  // Dump vars to the output .vcd file
  $dumpvars(0, main_tb);
 
  // TODO: initialize the registers here
  // e.g. value = 1;
  // e.g. #2 value = 0;
 
  #(DURATION) $display("End of simulation");
  $finish;
 end
 
endmodule
