# readthedocs.yaml
# Configuración para Read the Docs

version: 2

build:
  os: "ubuntu-22.04"
  tools:
    python: "3.10"

python:
  install:
    - requirements: docs-old-redirect/requirements.txt

sphinx:
  configuration: docs-old-redirect/docs/conf.py

