// Protocol buffers definitions used by apio.  Currently we use them just
// for passing parameters from the apio process to the scons process.

// IMPORTANT: After making changes in this file, run the command 'update-proto.sh'
// to propagate them to the python stubs. Otherwise they do not take affect.

// Online proto formatter at https://formatter.org/protobuf-formatter

// NOTE: Since we use the the serialized proto data within a single invocation
// of apio, protocol buffers text mode and binary mode backward compatibility
// considerations do not apply.

// Using proto2 for features such as 'has' and 'required'.
syntax = "proto2";


package apio.common.proto;

// The supported FPGA architectures. We use lower case name for compatibility
// with with json since proto enum values don't support [json_name=] 
// override.
enum ApioArch {
  ice40 = 1;
  ecp5 = 2;
  gowin = 3;
  xilinx = 4;
}


