// Code generated by Icestudio 0.12.1w202410070310202410070310
// Mon, 07 Oct 2024 14:01:06 GMT

`default_nettype none

//---- Top entity
module main (
 output v8bfc7f
);
 wire w0;
 assign v8bfc7f = w0;
 vfebcfe vb9eb2f (
  .v9fb85f(w0)
 );
endmodule

//---- Top entity
module vfebcfe (
 output v9fb85f
);
 wire w0;
 assign v9fb85f = w0;
 vfebcfe_vb2eccd vb2eccd (
  .q(w0)
 );
endmodule

//---------------------------------------------------
//-- bit-1
//-- - - - - - - - - - - - - - - - - - - - - - - - --
//-- Constant bit 1
//---------------------------------------------------

module vfebcfe_vb2eccd (
 output q
);
 //-- Constant bit-1
 assign q = 1'b1;
 
 
endmodule
