# *** Apio patched line:
# pylint: disable=all

# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: apio-resources.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'apio-resources.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14\x61pio-resources.proto\x12\x11\x61pio.common.proto\"\xb4\x01\n\nApioConfig\x12\x36\n\x16remote_config_ttl_days\x18\x01 \x02(\x05R\x16remote-config-ttl-days\x12@\n\x1bremote_config_retry_minutes\x18\x02 \x02(\x05R\x1bremote-config-retry-minutes\x12,\n\x11remote_config_url\x18\x03 \x02(\tR\x11remote-config-url\"\x82\x03\n\x12\x41pioPackageEnvSpec\x12 \n\x0b\x61\x64\x64_to_path\x18\x02 \x03(\tR\x0b\x61\x64\x64-to-path\x12(\n\x0f\x64\x65lete_env_vars\x18\x01 \x03(\tR\x0f\x64\x65lete-env-vars\x12Y\n\x0c\x61\x64\x64_env_vars\x18\x03 \x03(\x0b\x32\x35.apio.common.proto.ApioPackageEnvSpec.AddEnvVarsEntryR\x0c\x61\x64\x64-env-vars\x12]\n\rdefine_consts\x18\x04 \x03(\x0b\x32\x37.apio.common.proto.ApioPackageEnvSpec.DefineConstsEntryR\rdefine-consts\x1a\x31\n\x0f\x41\x64\x64\x45nvVarsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\x1a\x33\n\x11\x44\x65\x66ineConstsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"\x94\x01\n\x0f\x41pioPackageSpec\x12\x13\n\x0b\x64\x65scription\x18\x01 \x02(\t\x12\x38\n\x17restricted_to_platforms\x18\x02 \x03(\tR\x17restricted-to-platforms\x12\x32\n\x03\x65nv\x18\x03 \x02(\x0b\x32%.apio.common.proto.ApioPackageEnvSpec')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'apio_resources_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_APIOPACKAGEENVSPEC_ADDENVVARSENTRY']._loaded_options = None
  _globals['_APIOPACKAGEENVSPEC_ADDENVVARSENTRY']._serialized_options = b'8\001'
  _globals['_APIOPACKAGEENVSPEC_DEFINECONSTSENTRY']._loaded_options = None
  _globals['_APIOPACKAGEENVSPEC_DEFINECONSTSENTRY']._serialized_options = b'8\001'
  _globals['_APIOCONFIG']._serialized_start=44
  _globals['_APIOCONFIG']._serialized_end=224
  _globals['_APIOPACKAGEENVSPEC']._serialized_start=227
  _globals['_APIOPACKAGEENVSPEC']._serialized_end=613
  _globals['_APIOPACKAGEENVSPEC_ADDENVVARSENTRY']._serialized_start=511
  _globals['_APIOPACKAGEENVSPEC_ADDENVVARSENTRY']._serialized_end=560
  _globals['_APIOPACKAGEENVSPEC_DEFINECONSTSENTRY']._serialized_start=562
  _globals['_APIOPACKAGEENVSPEC_DEFINECONSTSENTRY']._serialized_end=613
  _globals['_APIOPACKAGESPEC']._serialized_start=616
  _globals['_APIOPACKAGESPEC']._serialized_end=764
# @@protoc_insertion_point(module_scope)
