# *** Apio patched line:
# pylint: disable=all

# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: apio-remote-config.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'apio-remote-config.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x18\x61pio-remote-config.proto\x12\x11\x61pio.common.proto\"@\n\x1aRemoteConfigRepositorySpec\x12\x0c\n\x04name\x18\x01 \x02(\t\x12\x14\n\x0corganization\x18\x02 \x02(\t\"7\n\x17RemoteConfigReleaseSpec\x12\x0b\n\x03tag\x18\x01 \x02(\t\x12\x0f\n\x07package\x18\x02 \x02(\t\"\x99\x01\n\x17RemoteConfigPackageSpec\x12\x41\n\nrepository\x18\x01 \x02(\x0b\x32-.apio.common.proto.RemoteConfigRepositorySpec\x12;\n\x07release\x18\x02 \x02(\x0b\x32*.apio.common.proto.RemoteConfigReleaseSpec\"\xb4\x01\n\x10RemoteConfigSpec\x12\x43\n\x08packages\x18\x01 \x03(\x0b\x32\x31.apio.common.proto.RemoteConfigSpec.PackagesEntry\x1a[\n\rPackagesEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\x39\n\x05value\x18\x02 \x01(\x0b\x32*.apio.common.proto.RemoteConfigPackageSpec:\x02\x38\x01\"\xaa\x01\n\x1a\x43\x61\x63hedRemoteConfigMetadata\x12\x1c\n\tloaded_by\x18\x01 \x02(\tR\tloaded-by\x12\x1c\n\tloaded_at\x18\x02 \x02(\tR\tloaded-at\x12 \n\x0bloaded_from\x18\x03 \x02(\tR\x0bloaded-from\x12.\n\x12refresh_failure_on\x18\x04 \x01(\tR\x12refresh-failure-on\"\xa4\x01\n\x16\x43\x61\x63hedRemoteConfigSpec\x12I\n\rremote_config\x18\x01 \x02(\x0b\x32#.apio.common.proto.RemoteConfigSpecR\rremote-config\x12?\n\x08metadata\x18\x02 \x02(\x0b\x32-.apio.common.proto.CachedRemoteConfigMetadata')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'apio_remote_config_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_REMOTECONFIGSPEC_PACKAGESENTRY']._loaded_options = None
  _globals['_REMOTECONFIGSPEC_PACKAGESENTRY']._serialized_options = b'8\001'
  _globals['_REMOTECONFIGREPOSITORYSPEC']._serialized_start=47
  _globals['_REMOTECONFIGREPOSITORYSPEC']._serialized_end=111
  _globals['_REMOTECONFIGRELEASESPEC']._serialized_start=113
  _globals['_REMOTECONFIGRELEASESPEC']._serialized_end=168
  _globals['_REMOTECONFIGPACKAGESPEC']._serialized_start=171
  _globals['_REMOTECONFIGPACKAGESPEC']._serialized_end=324
  _globals['_REMOTECONFIGSPEC']._serialized_start=327
  _globals['_REMOTECONFIGSPEC']._serialized_end=507
  _globals['_REMOTECONFIGSPEC_PACKAGESENTRY']._serialized_start=416
  _globals['_REMOTECONFIGSPEC_PACKAGESENTRY']._serialized_end=507
  _globals['_CACHEDREMOTECONFIGMETADATA']._serialized_start=510
  _globals['_CACHEDREMOTECONFIGMETADATA']._serialized_end=680
  _globals['_CACHEDREMOTECONFIGSPEC']._serialized_start=683
  _globals['_CACHEDREMOTECONFIGSPEC']._serialized_end=847
# @@protoc_insertion_point(module_scope)
