# *** Apio patched line:
# pylint: disable=all

# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: apio-parts-indexes.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'apio-parts-indexes.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


# *** Apio patched line:
from . import apio_common_pb2 as apio__common__pb2
# *** Apio patched line:
from . import apio_definitions_pb2 as apio__definitions__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x18\x61pio-parts-indexes.proto\x12\x11\x61pio.common.proto\x1a\x11\x61pio-common.proto\x1a\x16\x61pio-definitions.proto\"Y\n\rApioPartEntry\x12\x11\n\tgenerated\x18\x01 \x02(\x08\x12\x35\n\ndefinition\x18\x02 \x02(\x0b\x32!.apio.common.proto.FpgaDefinition')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'apio_parts_indexes_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_APIOPARTENTRY']._serialized_start=90
  _globals['_APIOPARTENTRY']._serialized_end=179
# @@protoc_insertion_point(module_scope)
