# -*- coding: utf-8 -*-
# ----------------------------------------------------------------------
# -- Generic Scons script for Sintesizing hardware on an FPGA and more.
# -- This file is part of the Apio project
# -- (C) 2016-2019 FPGAwars
# -- Authors Juan Gonzáles, Jesús Arroyo
# -- Licence GPLv2
# ----------------------------------------------------------------------

import os
import re
from platform import system
from SCons.Script import (Builder, Action, DefaultEnvironment, Default, AlwaysBuild,
                          GetOption, Exit, COMMAND_LINE_TARGETS, ARGUMENTS,
                          Variables, Help, Glob)
from apio.scons_util import (get_constraint_file, error, fatal_error, 
                             create_construction_env, arg_bool, arg_str)

# -- Create the environment
env = create_construction_env(ARGUMENTS)

# -- Load arguments
PROG = arg_str(env, 'prog', '')
FPGA_SIZE = arg_str(env, 'fpga_size', '')
FPGA_TYPE = arg_str(env, 'fpga_type', '')
FPGA_PACK = arg_str(env, 'fpga_pack', '')
TOP_MODULE = arg_str(env, 'top_module', '')
VERBOSE_ALL = arg_bool(env, 'verbose_all', False)
VERBOSE_YOSYS = arg_bool(env, 'verbose_yosys', False)
VERBOSE_PNR = arg_bool(env, 'verbose_pnr', False)
TESTBENCH = arg_str(env, 'testbench', '')
VERILATOR_ALL = arg_bool(env, 'all', False)
VERILATOR_NO_STYLE = arg_bool(env, 'nostyle', False)
VERILATOR_NO_WARN = arg_str(env, 'nowarn', '').split(',')
VERILATOR_WARN = arg_str(env, 'warn', '').split(',')
VERILATOR_TOP = arg_str(env, 'top', '')

VERILATOR_PARAM_STR = ''
for warn in VERILATOR_NO_WARN:
    if warn != '':
        VERILATOR_PARAM_STR += ' -Wno-' + warn

for warn in VERILATOR_WARN:
    if warn != '':
        VERILATOR_PARAM_STR += ' -Wwarn-' + warn


# -- Just for debugging
if 'build' in COMMAND_LINE_TARGETS or \
   'upload' in COMMAND_LINE_TARGETS or \
   'time' in COMMAND_LINE_TARGETS:

    # print('FPGA_SIZE: {}'.format(FPGA_SIZE))
    # print('FPGA_TYPE: {}'.format(FPGA_TYPE))
    # print('FPGA_PACK: {}'.format(FPGA_PACK))

    if 'upload' in COMMAND_LINE_TARGETS:
        if PROG == '':
            fatal_error(env, 'No programmer command found.')
        assert "${SOURCE}" in PROG, f"{PROG = }"


# -- Resources paths
IVL_PATH = os.environ['IVL'] if 'IVL' in os.environ else ''
ICEBOX_PATH = os.environ['ICEBOX'] if 'ICEBOX' in os.environ else ''
CHIPDB_PATH = os.path.join(ICEBOX_PATH, 'chipdb-{0}.txt'.format(FPGA_SIZE))
YOSYS_PATH = os.environ['YOSYS_LIB'] if 'YOSYS_LIB' in os.environ else ''
YOSYS_CELLS_PATH = f"{YOSYS_PATH}/ice40/cells_sim.v"

isWindows = 'Windows' == system()
VVP_PATH = '' if isWindows or not IVL_PATH else '-M "{0}"'.format(IVL_PATH)
IVER_PATH = '' if isWindows or not IVL_PATH else '-B "{0}"'.format(IVL_PATH)

# -- Target name
TARGET = 'hardware'

# -- Scan required .list files
list_files_re = re.compile(r'[\n|\s][^\/]?\"(.*\.list?)\"', re.M)


def list_files_scan(node, env, path):
    contents = node.get_text_contents()
    includes = list_files_re.findall(contents)
    return env.File(includes)


list_scanner = env.Scanner(function=list_files_scan)

# -- Get a list of all the verilog files in the src folfer, in ASCII, with
# -- the full path. All these files are used for the simulation
v_nodes = Glob('*.v')
v_files = [str(f) for f in v_nodes]

# Construct disjoint lists of .v module and testbench files.
src_synth = [f for f in v_files if f[-5:].upper() != '_TB.V']
list_tb = [f for f in v_files if f[-5:].upper() == '_TB.V']

# -- Get the PCF file name.
PCF = get_constraint_file(env, ".pcf", TOP_MODULE)

# -- Synthesizing Builder
synth_builder = Builder(
    action='yosys -p \"synth_ice40 {0} -json $TARGET\" {1} $SOURCES'.format(
        ('-top '+TOP_MODULE) if TOP_MODULE else '',
        '' if VERBOSE_ALL or VERBOSE_YOSYS else '-q'
    ),
    suffix='.json',
    src_suffix='.v',
    source_scanner=list_scanner)
env.Append(BUILDERS={'Synth': synth_builder})

# -- Place and route Builder.
pnr_builder = Builder(
    action='nextpnr-ice40 --{0}{1} --package {2} --json $SOURCE --asc $TARGET --pcf {3} {4}'.format(
        FPGA_TYPE, FPGA_SIZE, FPGA_PACK, PCF,
        '' if VERBOSE_ALL or VERBOSE_PNR else '-q'),
    suffix='.asc',
    src_suffix='.json')
env.Append(BUILDERS={'PnR': pnr_builder})

# -- Bitstream Builder.
bitstream_builder = Builder(
    action='icepack $SOURCE $TARGET',
    suffix='.bin',
    src_suffix='.asc')
env.Append(BUILDERS={'Bin': bitstream_builder})

# -- Time report builder
# https://github.com/cliffordwolf/icestorm/issues/57
time_rpt_builder = Builder(
    action='icetime -d {0}{1} -P {2} -C "{3}" -mtr $TARGET $SOURCE'.format(
        FPGA_TYPE, FPGA_SIZE, FPGA_PACK, CHIPDB_PATH),
    suffix='.rpt',
    src_suffix='.asc')
env.Append(BUILDERS={'Time': time_rpt_builder})

# -- Generate the bitstream
blif_target = env.Synth(TARGET, [src_synth])
asc_target = env.PnR(TARGET, [blif_target, PCF])
bitstream_target = env.Bin(TARGET, asc_target)

build_target = env.Alias('build', bitstream_target)
AlwaysBuild(build_target)

if(VERBOSE_ALL or VERBOSE_YOSYS):
    AlwaysBuild(blif_target)
if(VERBOSE_ALL or VERBOSE_PNR):
    AlwaysBuild(asc_target)

# -- Upload the bitstream into FPGA
programmer = PROG.replace("${SOURCE}", "$SOURCE")
upload_target = env.Alias('upload', bitstream_target, programmer)
AlwaysBuild(upload_target)

# -- Target time: calculate the time
rpt_target = env.Time(asc_target)
AlwaysBuild(rpt_target) 
time_target = env.Alias('time', rpt_target)

# -- Icarus Verilog builders

def iverilog_generator(source, target, env, for_signature):
    """Constructs dynamically a commands for iverlog targets builders. """
    target_name, _  = os.path.splitext(str(target[0]))  # E.g. "my_module" or"my_module_tb"
    # Testbenches use the value macro VCD_OUTPUT to know the name of the waves output file.
    # We also pass a dummy when the verify command to avoid a warning about the undefined macro. 
    is_testbench = target_name.upper().endswith("_TB")
    is_verify = 'verify' in COMMAND_LINE_TARGETS
    vcd_output_flag = (
        f'-D VCD_OUTPUT=dummy_vcd_output'  if is_verify 
        else  f'-D VCD_OUTPUT={target_name}' if is_testbench 
        else  "")
    verbose_flag = '-v' if VERBOSE_ALL else ''
    # If running a testbench with the sim command, we define the macro INTERACTIVE_SIM that
    # allows the testbench to supress assertions so we can examine the waves in gtkwave. 
    # For example, with an assertion macro like this one that fails when running apio test.
    # `define EXPECT(signal, value) \
    #     if (signal !== value) begin \
    #         $display("ASSERTION FAILED in %m: signal != value"); \
    #         `ifndef INTERACTIVE_SIM \
    #             $fatal; \
    #         `endif \
    #     end
    is_interactive_sim = is_testbench and 'sim' in COMMAND_LINE_TARGETS
    interactive_sim_flag = f'-D INTERACTIVE_SIM' if is_interactive_sim else ""
    result = 'iverilog {0} {1} -o $TARGET {2} {3} -D NO_ICE40_DEFAULT_ASSIGNMENTS "{4}" $SOURCES'.format(
        IVER_PATH, verbose_flag, vcd_output_flag, interactive_sim_flag, YOSYS_CELLS_PATH)
    return result

iverilog_builder = Builder(
    # Action string is computed automatically by the generator.
    generator = iverilog_generator,
    suffix='.out',
    src_suffix='.v',
    source_scanner=list_scanner)
env.Append(BUILDERS={'IVerilog': iverilog_builder})

dot_builder = Builder(
    action='yosys -f verilog -p \"show -format dot -colors 1 -prefix hardware {0}\" {1} $SOURCES'.format(
        TOP_MODULE if TOP_MODULE else 'unknown_top',
        '' if VERBOSE_ALL else '-q'
    ),
    suffix='.dot',
    src_suffix='.v',
    source_scanner=list_scanner)
env.Append(BUILDERS={'DOT': dot_builder})

svg_builder = Builder(
    # Expecting graphviz dot to be installed and in the path.
    action='dot -Tsvg $SOURCES -o $TARGET',
    suffix='.svg',
    src_suffix='.dot',
    source_scanner=list_scanner)
env.Append(BUILDERS={'SVG': svg_builder})

# NOTE: output file name is defined in the iverilog call using VCD_OUTPUT macro
vcd_builder = Builder(
    action='vvp {0} $SOURCE'.format(
        VVP_PATH),
    suffix='.vcd',
    src_suffix='.out')
env.Append(BUILDERS={'VCD': vcd_builder})

# --- Verify
vout_target = env.IVerilog(TARGET, src_synth + list_tb)
AlwaysBuild(vout_target)
verify_target = env.Alias('verify', vout_target)

# --- Graph
# TODO: Launch some portable SVG (or differentn format) viewer.
dot_target = env.DOT(TARGET, src_synth)
AlwaysBuild(dot_target)
svg_target = env.SVG(TARGET, dot_target)
AlwaysBuild(svg_target)
graph_target = env.Alias('graph', svg_target)

# --- Simulation
# Since the simulation targets are dynamic due to the testbench selection, we 
# create them only when running simulation.
if 'sim' in COMMAND_LINE_TARGETS: 
    assert 'test' not in COMMAND_LINE_TARGETS, COMMAND_LINE_TARGETS
    if TESTBENCH:
        # Explicit testbench file name is given via --testbench.
        sim_testbench = TESTBENCH
    else:
        # No --testbench flag specified. If there is exactly one testbench then pick
        # it, otherwise fail. 
        if len(list_tb) == 0:
            fatal_error(env, 'No testbench found for simulation.')
        if len(list_tb) > 1:
            # TODO: consider to allow specifying the default testbench in apio.ini.
            error(env, 'Found {} testbranches, please use the --testbench flag.'.format(len(list_tb)))
            for tb in list_tb:
                print('- {}'.format(tb))
            Exit(1)
        sim_testbench = list_tb[0]  # Pick the only available testbench.
    # Here sim_testbench contains the testbench, e.g. my_module_tb.v.
    # Construct list of files to build.
    src_sim = []
    src_sim.extend(src_synth)  # All the .v files.
    src_sim.append(sim_testbench)
    # Create targets sim target and its dependent.
    sim_name, _ = os.path.splitext(sim_testbench)  #e.g. my_module_tb
    sout_target = env.IVerilog(sim_name, src_sim)
    vcd_file_target = env.VCD(sout_target)
    # 'do_initial_zoom_fit' does max zoom only if .gtkw file not found.
    waves_target = env.Alias('sim', vcd_file_target, 'gtkwave {0} {1} {2}.gtkw'.format(
        '--rcvar "splash_disable on" --rcvar "do_initial_zoom_fit 1"',
        vcd_file_target[0], sim_name))
    AlwaysBuild(waves_target)


# --- Testing
# Since the simulation targets are dynamic due to the testbench selection, we 
# create them only when running simulation.
if 'test' in COMMAND_LINE_TARGETS: 
    assert 'sim' not in COMMAND_LINE_TARGETS, COMMAND_LINE_TARGETS
    if TESTBENCH:
        # Explicit testbench file name is given via --testbench. We test just that one.
        test_tbs= [ TESTBENCH ]
    else:
        # No --testbench flag specified. We will test all them.
        if len(list_tb) == 0:
            fatal_error(env, 'No testbench files found (*_tb.v).')
        test_tbs= list_tb  # All testbenches.
    tests = [] # Targets of all tests
    for test_tb in test_tbs:
        # Create a list of source files. All the modules + the current testbench.
        src_test = []
        src_test.extend(src_synth)  # All the .v files.
        src_test.append(test_tb)
        # Create the targets for the 'out' and 'vcd' files of the testbench.
        # NOTE: Remove the two AlwaysBuild() calls below for an incremental test. Fast, correct,
        # but may confuse the user seeing nothing happens. 
        test_name, _ = os.path.splitext(test_tb)  #e.g. my_module_tb
        test_out_target = env.IVerilog(test_name, src_test)
        AlwaysBuild(test_out_target)
        test_vcd_target = env.VCD(test_out_target)
        AlwaysBuild(test_vcd_target)
        test_target = env.Alias(test_name, [test_out_target, test_vcd_target])
        tests.append(test_target)
    # Create a target for the test command that depends on all the test targets.
    tests_target = env.Alias('test', tests)
    AlwaysBuild(tests_target)

# -- Verilator config file builder
def verilator_config_func(target, source, env):
        with open(target[0].get_path(), 'w') as target_file:
            target_file.write('`verilator_config\n'
                f'lint_off -rule COMBDLY      -file "{YOSYS_CELLS_PATH}"\n'
                f'lint_off -rule WIDTHEXPAND  -file "{YOSYS_CELLS_PATH}"\n')
        return 0

verilator_config_builder = Builder(
    action=Action(verilator_config_func, "Creating verilator config file."),
    suffix='.vlt',
    source_scanner=list_scanner)
env.Append(BUILDERS={'VerilatorConfig': verilator_config_builder})

# -- Verilator builder
verilator_builder = Builder(
    action='verilator --lint-only --bbox-unsup --timing -Wno-TIMESCALEMOD -Wno-MULTITOP -DNO_ICE40_DEFAULT_ASSIGNMENTS {0} {1} {2} {3} $SOURCES "{4}"'.format(
        '-Wall' if VERILATOR_ALL else '',
        '-Wno-style' if VERILATOR_NO_STYLE else '',
        VERILATOR_PARAM_STR if VERILATOR_PARAM_STR else '',
        '--top-module ' + VERILATOR_TOP if VERILATOR_TOP else '',
        YOSYS_CELLS_PATH),
    src_suffix='.v',
    source_scanner=list_scanner)
env.Append(BUILDERS={'Verilator': verilator_builder})

# --- Lint
lint_config_target = env.VerilatorConfig(TARGET, [])
lint_out_target = env.Verilator(TARGET, [TARGET + ".vlt"] + src_synth + list_tb)
lint_target = env.Alias('lint', lint_out_target)
AlwaysBuild(lint_target)

Default(bitstream_target)

# -- These is for cleaning the artifact files.
if GetOption('clean'):
    # Identify additional files that may not be associated with targets and
    # associate them with a target such that they will be cleaned up as well.
    # This cleans for example artifacts of past simulation since the testbench
    # target are dynamic and changes with the selected testbench.
    for glob_pattern in ['*.out', '*.vcd']:
        for node in Glob(glob_pattern):
            env.Clean(time_target, str(node))

    env.Default([time_target, build_target, vout_target, graph_target, lint_target])

