// Code generated by Icestudio 0.8.1w202112300112

`default_nettype none

//---- Top entity
module main (
 output v6e100e,
 output v0b941e,
 output v2a3480
);
 wire w0;
 wire w1;
 wire w2;
 assign v0b941e = w0;
 assign v6e100e = w1;
 assign v2a3480 = w2;
 vfebcfe v7dc4a3 (
  .v9fb85f(w0)
 );
 vfebcfe va834d8 (
  .v9fb85f(w1)
 );
 vd30ca9 v9ceafe (
  .v9fb85f(w2)
 );
endmodule

//---- Top entity
module vfebcfe (
 output v9fb85f
);
 wire w0;
 assign v9fb85f = w0;
 vfebcfe_vb2eccd vb2eccd (
  .q(w0)
 );
endmodule

//---------------------------------------------------
//-- bit-1
//-- - - - - - - - - - - - - - - - - - - - - - - - --
//-- Constant bit 1
//---------------------------------------------------

module vfebcfe_vb2eccd (
 output q
);
 //-- Constant bit-1
 assign q = 1'b1;
 
 
endmodule
//---- Top entity
module vd30ca9 (
 output v9fb85f
);
 wire w0;
 assign v9fb85f = w0;
 vd30ca9_vb2eccd vb2eccd (
  .q(w0)
 );
endmodule

//---------------------------------------------------
//-- bit-0
//-- - - - - - - - - - - - - - - - - - - - - - - - --
//-- Constant bit 0
//---------------------------------------------------

module vd30ca9_vb2eccd (
 output q
);
 //-- Constant bit-0
 assign q = 1'b0;
 
 
endmodule
