// Code generated by Icestudio 0.9.2w202204260904
// Thu, 28 Apr 2022 08:42:19 GMT

// Testbench template

`default_nettype none
`define DUMPSTR(x) `"x.vcd`"
`timescale 10 ps / 1 ps


module main_tb
;
 
 // Simulation time: 100ns (10 * 10ns)
 parameter DURATION = 50;
 
//-- Clock signal
reg clk = 0;
always #4.2 clk = ~clk;

 // Input/Output
 wire LED_test;
 
 // Module instance
 main MAIN (
  .vclk(clk),
  .v8bfc7f(LED_test)
 );
 
 initial begin
  // File were to store the simulation results
  $dumpfile(`DUMPSTR(`VCD_OUTPUT));
  $dumpvars(0, main_tb);
 
  // TODO: initialize the registers here
  // e.g. value = 1;
  // e.g. #2 value = 0;
 
  #(DURATION) $display("End of simulation");
  $finish;
 end
 
endmodule
