// Common protcol buffers definitions that are imported by other
// protocol buffer files.

// IMPORTANT: After making changes in this file, run the repo task
// 'invoke update-protos' to propagate them to the python stubs.
//  Otherwise they do not take affect.

// Using proto2 for features such as 'has' and 'required'.
syntax = "proto2";


package apio.common.proto;

// The supported FPGA architectures.
// Using lower case names to be json friendly.
enum ApioArch {
  ice40 = 1;
  ecp5 = 2;
  gowin = 3;
  xilinx = 4;
}

