# pylint: disable=all

# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: apio/common/proto/apio-testing.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'apio/common/proto/apio-testing.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n$apio/common/proto/apio-testing.proto\x12\x11\x61pio.common.proto\"B\n\x08MessageA\x12\x1a\n\x08\x66ield_a1\x18\x01 \x02(\tR\x08\x66ield-a1\x12\x1a\n\x08\x66ield_a2\x18\x02 \x01(\tR\x08\x66ield-a2\"|\n\x08MessageB\x12\x37\n\x08\x66ield_b1\x18\x01 \x02(\x0b\x32\x1b.apio.common.proto.MessageAR\x08\x66ield-b1\x12\x37\n\x08\x66ield_b2\x18\x02 \x01(\x0b\x32\x1b.apio.common.proto.MessageAR\x08\x66ield-b2')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'apio.common.proto.apio_testing_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_MESSAGEA']._serialized_start=59
  _globals['_MESSAGEA']._serialized_end=125
  _globals['_MESSAGEB']._serialized_start=127
  _globals['_MESSAGEB']._serialized_end=251
# @@protoc_insertion_point(module_scope)
