# A periodic workflow to crawl, analyze, fix, clean, and verify the
# Apio's repositories.

name: apio-repos-janitor

on:
  # Run on commit.
  push:

  # Run every 6 hours
  # schedule:
  #   - cron: "0 */6 * * *"

  # Allow manual launch
  workflow_dispatch:

jobs:
  janitor:
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash

    steps:
      # -- We need the apio repo for the janitor scripts.
      - name: Checkout Apio's main branch
        uses: actions/checkout@v5
        with:
          ref: main

      - name: Set up latest Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.14"

      - name: Install python dependencies
        run: |
          pip install -r scripts/janitor/requirements.txt

      - name: Run the crawler
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          python -m scripts.janitor.crawler --janitor-data-dir ./_janitor-data

      - name: Show crawler results
        run: |
          cat ./_janitor-data/crawl-results.json

      - name: Run the analyzer
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          python -m scripts.janitor.analyzer --janitor-data-dir ./_janitor-data

      - name: Show analyzer results
        run: |
          cat ./_janitor-data/analysis-results.json

      - name: Run the verifier
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          python -m scripts.janitor.verifier --janitor-data-dir ./_janitor-data

      - name: Show verifier results
        run: |
          cat ./_janitor-data/verification-results.json

     

  

      - name: Write verification report to summary
        run: |
          {
            cat ./_janitor-data/verification-results.md
          } >> "$GITHUB_STEP_SUMMARY"

      - name: Write verification results to summary
        run: |
          {
            echo
            echo '## Verification results'
            echo
            echo '```json'
            cat ./_janitor-data/verification-results.json
            echo
            echo '```'
          } >> "$GITHUB_STEP_SUMMARY"

      - name: Upload json and report files as an artifact
        uses: actions/upload-artifact@v6
        with:
          name: janitor-json
          path: |
            ./_janitor-data/*.json
            ./_janitor-data/*.md
          if-no-files-found: error

      - name: Fail if verifications has failures
        run: |
          # -- Dump failures, if any
          jq '{failures: .failures}' _janitor-data/verification-results.json
          # -- Fail if passed is not true.
          jq -e '.passed == true' ./_janitor-data/verification-results.json > /dev/null
