name: build-linux-x86-64-installer

on:
  schedule:
    - cron: '0 0 * * *'  # Runs daily at midnight UTC
  workflow_dispatch:  # Manual triggers ok.


jobs:
  build-linux-x86-64-installer:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash  # Set Bash as the default shell

    steps:
      - name: Log architecture info
        # Expecting 'x86_64'
        run: uname -m

      - name: Install Snapcraft
        run: |
          sudo apt update
          sudo apt install -y snapd
          sudo snap install snapcraft --classic
          snapcraft --version
  
      - name: Install python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'  # Adjust version as needed


      - name: Checkout the apio repo
        uses: actions/checkout@v4
        with:
          path: apio-repo


      - name: Pip install apio.
        run: |
          python -m pip install --upgrade pip
          pip install -e apio-repo


      - name: Pip install pyinstaller
        run: |
          pip install pyinstaller


      - name: Extract apio version
        run: |
          echo "APIO_VERSION=$(pip show apio | grep Version: | cut -d ' ' -f2)" >> $GITHUB_ENV


      - name: Echo apio version
        run: |
          echo "$APIO_VERSION"


      - name: Setup working directories.
        run: |
          mkdir _work
          mkdir _dist
          mkdir _snap
          pwd
          ls -la .


      - name: Run pyinstaller
        run: |
          pyinstaller \
            --workpath _work \
            --distpath _dist \
            apio-repo/.github/workflows/resources/apio-pyinstaller.spec
          echo "_dist:"
          ls -al _dist
          echo "_dist/apio:"
          ls -al _dist/apio

      - name: Check for symlinks
        run: |
          # If _dist/_internal contains symlinks, we need to revisit how
          # we copy it around, while preserving symlinks. May need to copy
          # using rsync, or just move it around instead of copying.
          if find _dist -type l | grep -q .; then
              echo "PyInstaller files contain symlinks"
              exit 1
          else
              echo "No symlinks"
          fi

      - name: Add LICENSE file
        run: |
          cp apio-repo/LICENSE _dist/apio
          echo "_dist:"
          ls -al _dist
          echo "_dist/apio:"
          ls -al _dist/apio


      - name: Add INFO file
        run: |
          info_file="_dist/apio/INFO"
          echo "Build information" >  ${info_file}
          echo "Time:         $(date +'%Y-%m-%d %H:%M:%S %Z')" >> ${info_file}
          echo "Run ID:       $GITHUB_RUN_ID" >> ${info_file}
          echo "Run number:   $GITHUB_RUN_NUMBER" >> ${info_file}
          echo "Commit SHA:   $GITHUB_SHA" >>  ${info_file}
          echo "Branch:       ${GITHUB_REF#refs/heads/}" >> ${info_file}
          echo "Repo owner:   $GITHUB_REPOSITORY_OWNER" >> ${info_file}
          echo "ReponName:    ${GITHUB_REPOSITORY#*/} ">> ${info_file}       
          echo "_dist/apio:"
          ls -al _dist/apio
          cat _dist/apio/INFO


      - name: Zip the pyinstaller package
        run: |
          pushd _dist
          package="apio-linux-x86-64-${{env.APIO_VERSION}}-pyinstaller.zip"
          zip -r -y ../${package} apio
          popd
          ls -al 


      - name: Create the snap package
        run: |     
          # Expand config template
          sed "s/\[APIO-VERSION\]/$APIO_VERSION/g" apio-repo/.github/workflows/linux-resources/snapcraft.template > _snap/snapcraft.yaml
          cat _snap/snapcraft.yaml

          # Populate the _snap directory
          cp _dist/apio/LICENSE _snap
          cp _dist/apio/INFO _snap

          # Populate the _snap/bin directory
          mkdir _snap/bin
          cp _dist/apio/apio _snap/bin
          cp -r _dist/apio/_internal _snap/bin
          echo
          ls -al _snap
          echo
          ls -al _snap/bin

          # Build snap package
          pushd _snap
          echo
          snapcraft --destructive-mode
          echo
          ls -al
          popd


      - name: Rename the snap package
        run: |
          mv _snap/apio_${APIO_VERSION}_amd64.snap apio-linux-x86-64-${{env.APIO_VERSION}}-snap.snap
          ls -al


      - name: Populate the debian package
        run: |
          mkdir _debian
          
          # -- /opt/apio
          mkdir -p _debian/opt/apio
          cp _dist/apio/apio _debian/opt/apio
          cp -r _dist/apio/_internal _debian/opt/apio
          
          # /usr/local/bin
          mkdir -p _debian/usr/local/bin
          pushd _debian/usr/local/bin
          ln -s ../../../opt/apio/apio apio
          popd
          
          # Package control file
          mkdir _debian/DEBIAN
          control="_debian/DEBIAN/control"
          sed "s/\[APIO-VERSION\]/$APIO_VERSION/g" apio-repo/.github/workflows/linux-resources/control.template > ${control}
          
          # Show info
          find _debian 
          cat ${control}

      - name: Set permissions for debian control file
        run: find _debian/DEBIAN -type f -exec chmod 644 {} \;

      - name: Build .deb package
        run: |
          dpkg-deb --build --root-owner-group _debian "apio-linux-x86-64-${APIO_VERSION}-debian.deb"
          ls -l 

     
      - name: Export the pyinstaller archive as an artifact.
        uses: actions/upload-artifact@v4
        with:
          if-no-files-found: error
          name: "apio-linux-x86-64-pyinstaller"
          path: "apio-linux-x86-64-${{env.APIO_VERSION}}-pyinstaller.zip"


      - name: Export the installer file as an artifact.
        uses: actions/upload-artifact@v4
        with:
          if-no-files-found: error
          name: "apio-linux-x86-64-debian"
          path: "apio-linux-x86-64-${{env.APIO_VERSION}}-debian.deb"


      - name: Export the snap package as an artifact.
        uses: actions/upload-artifact@v4
        with:
          if-no-files-found: error
          name: "apio-linux-x86-64-snap"
          path: "apio-linux-x86-64-${{env.APIO_VERSION}}-snap.snap"


      - name: Write a summary message
        run: |
          echo "NOTE: Github wraps the artifact files with an additional level of zip archive."    >> $GITHUB_STEP_SUMMARY
          echo "To retrieve the artifact files, unzip the zip files you download from this page."  >> $GITHUB_STEP_SUMMARY       
