name: build-darwin-arm64-installer

on:
  # For now we use only manual triggers.
  workflow_dispatch:  # 👈 Enables manual trigger

jobs:
  build-darwin-arm64-installer:
    runs-on: macos-latest

    steps:
      - name: Install python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'  # Adjust version as needed


      - name: Checkout the apio repo
        uses: actions/checkout@v4
        with:
          path: apio-repo


      - name: Pip install apio.
        run: |
          python -m pip install --upgrade pip
          pip install -e apio-repo


      - name: Pip install pyinstaller
        run: |
          pip install pyinstaller


      - name: Extract apio version
        run: |
          echo "APIO_VERSION=$(pip show apio | grep Version: | cut -d ' ' -f2)" >> $GITHUB_ENV


      - name: Echo apio version
        run: |
          echo "$APIO_VERSION"


      - name: Setup working directories.
        run: |
          mkdir _work
          mkdir _dist
          pwd
          ls -la .


      - name: Run pyinstaller
        run: |
          pyinstaller \
            --workpath _work \
            --distpath _dist \
            apio-repo/.github/workflows/resources/apio-pyinstaller.spec
          echo "_dist:"
          ls -al _dist
          echo "_dist/apip:"
          ls -al _dist/apio

      - name: Add resource files
        run: |
          cp apio-repo/LICENSE.txt _dist/apio
          echo "_dist:"
          ls -al _dist
          echo "_dist/apip:"
          ls -al _dist/apio


      - name: Run pkgbuild
        run: |
          pkgbuild --root _dist \
                   --install-location /Applications \
                   --identifier "io.github.fpgawars.apio" \
                   --version "${{env.APIO_VERSION}}" \
                   --scripts apio-repo/.github/workflows/resources/darwin-scripts \
                   --ownership recommended \
                   apio-component.pkg
          pwd
          ls -al


      - name: Run productbuild
        run: |
          productbuild --resources apio-repo/.github/workflows/resources/darwin-installer-resources \
                       --distribution apio-repo/.github/workflows/resources/darwin-installer-distribution.xml \
                       --package-path . \
                       "apio-darwin-arm64-${{env.APIO_VERSION}}-installer.pkg"
          pwd
          ls -al


      - name: Export the installer file as an artifact.
        uses: actions/upload-artifact@v4
        with:
          name: "apio-darwin-arm64-${{env.APIO_VERSION}}-installer"
          path: "apio-darwin-arm64-${{env.APIO_VERSION}}-installer.pkg"

      
