# -- Publish to PyPi an pre-built Apio release.

name: publish-to-pypi

# -- Manual activation
on:
  workflow_dispatch:
    inputs:
      release_tag:
        description: "Apio CLI release tag on this repo, e.g. 2025-12-10"
        required: true
        type: string

env:
  # -- Set latter.
  RELEASE_COMMIT_SHA: ""

jobs:
  # -- Publish a new Apio release
  publish:
    runs-on: ubuntu-22.04
    steps:
      - name: Check that the release tag has yyyy-mm-dd format.
        uses: fpgawars/apio-workflows/.github/actions/check-release-tag@main
        with:
          release-tag: ${{ inputs.release_tag }}

      - name: Check that the release is stable
        uses: fpgawars/apio-workflows/.github/actions/check-release-is-stable@main
        with:
          release-repo: ${{ github.repository }}
          release-tag: ${{ inputs.release_tag }}

      - name: Get release and package tags.
        run: |
          RELEASE_TAG="${{ inputs.release_tag }}"
          echo "RELEASE_TAG=$RELEASE_TAG"
          echo "RELEASE_TAG=$RELEASE_TAG" >> "$GITHUB_ENV"

          PACKAGE_TAG="${RELEASE_TAG//-/}"
          echo "PACKAGE_TAG=$PACKAGE_TAG"
          echo "PACKAGE_TAG=$PACKAGE_TAG" >> "$GITHUB_ENV"

      # -- Install and and configure python
      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.13"

      # -- Install python dependencies.
      - name: Install python dependencies
        run: |
          python -m pip install --upgrade pip twine

      - name: Fetch pypi package archive from the release
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          gh release download "$RELEASE_TAG" \
            --repo "${{ github.repository }}" \
            --pattern "apio-pypi-package-${PACKAGE_TAG}.tgz"
          ls -al

      - name: Unpack the pypi package archive
        run: |
          tar -xzf "apio-pypi-package-${PACKAGE_TAG}.tgz"
          ls -al dist

      - name: List package files
        run: |
          tar -tzf dist/apio-*.tar.gz | tree --fromfile .

      - name: Extract BUILD-INFO.json file
        run: |
          tar -xOzf dist/apio-*.tar.gz --wildcards --no-anchored '*/apio/BUILD-INFO.json' > BUILD-INFO.json
          cat -n BUILD-INFO.json

      - name: Append BUILD-INFO.json to workflow summary
        run: |
          {
            echo '### BUILD-INFO.json'
            echo
            echo '```json'
            cat BUILD-INFO.json
            echo
            echo '```'
          } >> "$GITHUB_STEP_SUMMARY"

      - name: Publish to PyPi
        env:
          # TODO: As of Dec 27 2025, PYPI_USERNAME and PYPI_PASSWORD
          # contain a token rather than the actual username and
          # password (good security). We copied PYPI_PASSWORD to
          # PYPI_API_TOKEN and use a literal "__token__" instead
          # of PYPI_USERNAME. Once this new configuration publishes
          # successfully, the two secrets PYPI_USERNAME and PYPI_PASSWORD
          # should be deleted for clarity.
          #
          # FLIT_USERNAME: ${{ secrets.PYPI_USERNAME }}
          # FLIT_PASSWORD: ${{ secrets.PYPI_PASSWORD }}

          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
        run: |
          python -m twine upload dist/*
