# ...

name: Test

on:
  push:
  # NOTE: We run the test daily, even if we don't push anything, to ensure
  # that the tests are still passing, despite potential changes in the github
  # dependencies.
  schedule:
    - cron: '0 0 * * *'  # Runs daily at midnight UTC
  workflow_dispatch:  # Allows manual trigger

jobs:
    test:
        runs-on: ${{ matrix.os }}

        defaults:
          run:
            shell: bash

        strategy:
            matrix:
                os: [ubuntu-22.04, macos-latest, windows-latest]
                python-version: ['3.11', '3.12', '3.13']

        steps:
            - name: Checkout sources
              uses: actions/checkout@v3

            - name: Set up Python
              uses: actions/setup-python@v4
              with:
                  python-version: ${{ matrix.python-version }}

            - name: Install dependencies
              run: |
                  make deps

            - name: Run Tests
              run: |
                  # Convert py version such as '3.13' to 'py313' as required by tox.ini.
                  pyver="py${{matrix.python-version}}"
                  echo "pyver: [$pyver]"
                  pyver=${pyver//./}
                  echo "pyver: [$pyver]"
                  python -m tox --skip-missing-interpreters false -e lint,$pyver

