# ...

name: Test

on:
  push:
  workflow_dispatch:  # Allows manual trigger

jobs:
    test:
        runs-on: ubuntu-22.04
        strategy:
            matrix:
                python-version: [3.9]

        steps:
            - name: Checkout sources
              uses: actions/checkout@v3

            - name: Set up Python
              uses: actions/setup-python@v4
              with:
                  python-version: ${{ matrix.python-version }}

            - name: Install dependencies
              run: |
                  make deps

            - name: Run Tests
              run: |
                  # Convert py version such as '3.13' to 'py313' as required by tox.ini.
                  pyver="py${{matrix.python-version}}"
                  pyver=${pyver//./}
                  echo "pyvar: [$pyvar]"
                  python -m tox --skip-missing-interpreters false -e lint,$pyver
                  
